### ISSUE TITLE
Open-Code-Interpreter can't chat with my data

### ISSUE THREAD

**Issue by Kreijstal** [haseeb-heaven/code-interpreter#5]
this is almost perfect, but I can only see the code the llm drops, I want to also chat with it, for debugging purposes, don't get me wrong, I want to execute code, but I want to ask questions, and do other things.

**Comment by haseeb-heaven** [comment]
> this is almost perfect, but I can only see the code the llm drops, I want to also chat with it, for debugging purposes, don't get me wrong, I want to execute code, but I want to ask questions, and do other things.

Okay create a Feature request and I will try to add them in next release.
Make sure to make it easy to understand what you want better give examples if needed.
Thanks.

**Comment by Kreijstal** [comment]
> > this is almost perfect, but I can only see the code the llm drops, I want to also chat with it, for debugging purposes, don't get me wrong, I want to execute code, but I want to ask questions, and do other things.
> 
> Okay create a Feature request and I will try to add them in next release. Make sure to make it easy to understand what you want better give examples if needed. Thanks.

for example I tried to tell me list all files in current directory, and it does that, then I told him, what do you think what is the best way to organize these files?
after some time, it came up with some code, but I wanted to see the thought-process, or chat with it.

**Comment by haseeb-heaven** [comment]
> > > this is almost perfect, but I can only see the code the llm drops, I want to also chat with it, for debugging purposes, don't get me wrong, I want to execute code, but I want to ask questions, and do other things.
> > 
> > 
> > Okay create a Feature request and I will try to add them in next release. Make sure to make it easy to understand what you want better give examples if needed. Thanks.
> 
> for example I tried to tell me list all files in current directory, and it does that, then I told him, what do you think what is the best way to organize these files? after some time, it came up with some code, but I wanted to see the thought-process, or chat with it.

Okay got it i need to implement memory for that to save conversations keep that in mind only GPT Bard and some other LLM's can have that memory but i will try to add that in next release.

**Comment by haseeb-heaven** [comment]
> > > this is almost perfect, but I can only see the code the llm drops, I want to also chat with it, for debugging purposes, don't get me wrong, I want to execute code, but I want to ask questions, and do other things.
> > 
> > 
> > Okay create a Feature request and I will try to add them in next release. Make sure to make it easy to understand what you want better give examples if needed. Thanks.
> 
> for example I tried to tell me list all files in current directory, and it does that, then I told him, what do you think what is the best way to organize these files? after some time, it came up with some code, but I wanted to see the thought-process, or chat with it.

I have Added Chat mode now in Version 1.9 download it from here.
https://pypi.org/project/open-code-interpreter/1.9.1/
