### ISSUE TITLE
Support for Gemini 1.5 Pro 

### ISSUE THREAD

**Issue by RehanPlayz** [haseeb-heaven/code-interpreter#8]
It supports a token count of 1 million+ and It supports both Images and Videos as well

Model: gemini-1.5-pro-Iatest

It is in private preview though, so not everyone has access to it yet.

**Comment by RehanPlayz** [comment]
> Hi, Thanks for your request yes i have access to that, but want to test via LiteLLM yet, will update from this issue ([BerriAI/litellm#1982](https://github.com/BerriAI/litellm/issues/1982))
> 
> I have also created new feature request to Google SDK ([google/generative-ai-python#227](https://github.com/google/generative-ai-python/issues/227))
> 
> Update: Google dev told me on **Discord** that its not available via **API/SDK** yet.

Ah I see, Thx for the response

**Comment by RehanPlayz** [comment]
https://developers.googleblog.com/2024/04/gemini-15-pro-in-public-preview-with-new-features.html?m=1

**Comment by haseeb-heaven** [comment]
> Gemini 1.5 Pro is now available through the API
> 
> https://developers.googleblog.com/2024/04/gemini-15-pro-in-public-preview-with-new-features.html?m=1

Thanks for sharing this.

**Comment by haseeb-heaven** [comment]
Waiting for LiteLLM to solve this issue https://github.com/BerriAI/litellm/issues/1982
